  GNU nano 4.8                                              wp-pv.yaml                                                         
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  nfs:
    path: /home/alrojasp/nfs
    server: 10.128.0.6



